<section class="content-row">
<h1 class="supporting title">Accordeon</h1>
<div class="accordion">
<h4><a href="#">Titel met H4</a></h4>
<div>
<p>Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.</p>
</div>
<h3><a href="#">Titel met H3</a></h3>
<div>
<p>Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.</p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">    &lt;div class="accordion"&gt;
    &lt;h4&gt;&lt;a href="#"&gt;Titel met H4&lt;/a&gt;&lt;/h4&gt;
    &lt;div&gt;
    &lt;p&gt;Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.&lt;/p&gt;
    &lt;/div&gt;
    &lt;h3&gt;&lt;a href="#"&gt;Titel met H3&lt;/a&gt;&lt;/h3&gt;
    &lt;div&gt;
    &lt;p&gt;Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.&lt;/p&gt;
    &lt;/div&gt;
    &lt;/div&gt;
        </textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<div>