<section class="content-row">
<h1 class="supporting title">Accordeon</h1>
<div class="accordion">
<h4><a href="#">Title with H4</a></h4>
<div>
<p>Every anchor tag within an H4 or H3 tag inside of a class='accordion' container will show the next child onclick. Accordeon style.</p>
</div>
<h3><a href="#">Title with H3</a></h3>
<div>
<p>Every anchor tag within an H4 or H3 tag inside of a class='accordion' container will show the next child onclick. Accordeon style.</p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">    &lt;div class="accordion"&gt;
    &lt;h4&gt;&lt;a href="#"&gt;Title with H4&lt;/a&gt;&lt;/h4&gt;
    &lt;div&gt;
    &lt;p&gt;Every anchor tag within an H4 or H3 tag inside of a class='accordion' container will show the next child onclick. Accordeon style.&lt;/p&gt;
    &lt;/div&gt;
    &lt;h3&gt;&lt;a href="#"&gt;Title with H3&lt;/a&gt;&lt;/h3&gt;
    &lt;div&gt;
    &lt;p&gt;Every anchor tag within an H4 or H3 tag inside of a class='accordion' container will show the next child onclick. Accordeon style.&lt;/p&gt;
    &lt;/div&gt;
    &lt;/div&gt;
        </textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>
<div>