<h1 class="supporting title">Call to actions</h1>
<p>Use the primary call to action for important actions, actions that convert. Example : lead them to a landingspage.</p>
<p><a class="action primary">Primary call to action</a></p>
<hr/>
<p>Use regular links for less important actions. Example : lead them to the delivery information.</p>
<p><a href="#">Regular link / less import call to action</a></p>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;p&gt;&lt;a class=&quot;action primary&quot;&gt;Primary call to action&lt;/a&gt;&lt;/p&gt;
&lt;p&gt;&lt;a href=&quot;#&quot;&gt;Regular link / less import call to action&lt;/a&gt;&lt;/p&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>