<h1 class="supporting title">Show more / less text</h1>
<p>I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship. I am the last of my species, and I know how that weighs on the heart so don't lie to me! It's a fez. I wear a fez now. Fezes are cool. It's a fez. I wear a fez now. Fezes are cool. I am the Doctor, and you are the Daleks! They're not aliens, they're Earth…liens! I am the last of my species, and I know how that weighs on the heart so don't lie to me! Saving the world with meals on wheels. You know how I sometimes have really brilliant ideas? I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship.</p>
<p><a class="showMoreText" href="#">More info</a></p>
<div class="moreText">
<p>No… It's a thing; it's like a plan, but with more greatness. Father Christmas. Santa Claus. Or as I've always known him: Jeff. You hit me with a cricket bat. You know how I sometimes have really brilliant ideas?</p>
<p><a class="showLessText" href="#">Minder info</a></p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">    &lt;h1&gt;Show more / less text&lt;/h1&gt;
    &lt;p&gt;I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship. I am the last of my species, and I know how that weighs on the heart so don't lie to me! It's a fez. I wear a fez now. Fezes are cool. It's a fez. I wear a fez now. Fezes are cool. I am the Doctor, and you are the Daleks! They're not aliens, they're Earth…liens! I am the last of my species, and I know how that weighs on the heart so don't lie to me! Saving the world with meals on wheels. You know how I sometimes have really brilliant ideas? I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship.&lt;/p&gt;
    &lt;p&gt;&lt;a class="showMoreText" href="#"&gt;More info&lt;/a&gt;&lt;/p&gt;
    &lt;div class="moreText"&gt;
    &lt;p&gt;No… It's a thing; it's like a plan, but with more greatness. Father Christmas. Santa Claus. Or as I've always known him: Jeff. You hit me with a cricket bat. You know how I sometimes have really brilliant ideas?&lt;/a&gt;&lt;/p&gt;
    &lt;/div&gt;
        </textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>