<h1 class="supporting title">Toon meer / minder tekst</h1>
<p>Heeft u geen garage, maar wel ruimte voor bijvoorbeeld een <strong>carport</strong>? Dan moet u zeker overwegen eentje aan te schaffen. Een carport is een overkapping voor uw auto en helpt uw auto te beschermen tegen vallende takken in de herfst, sneeuw en hagel. U hebt geen afdrukken van hagelbollen meer &eacute;n u hoeft geen sneeuw meer van uw voorruit te schuiven. Ten opzichte van een garage is een carport een veel goedkopere oplossing en biedt deze ook voldoende bescherming.</p>
<p><a class="showMoreText" href="#">Meer info</a></p>
<div class="moreText">
<p>Dat u niet lukraak een carport kiest begrijpen we. Daarom hebben we verschillende types carports voor verschillende types van woningen in ons assortiment. Bekijk ook de verschillende afmetingen. Naargelang u een grote of kleine wagen heeft kan u een carport van een andere lengte kiezen. Bekijk ons assortiment hieronder!</p>
<p><a class="showLessText" href="#">Minder info</a></p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">    &lt;h1&gt;Show more / less text&lt;/h1&gt;
    &lt;p&gt;Heeft u geen garage, maar wel ruimte voor bijvoorbeeld een &lt;strong&gt;carport&lt;/strong&gt;? Dan moet u zeker overwegen eentje aan te schaffen. Een carport is een overkapping voor uw auto en helpt uw auto te beschermen tegen vallende takken in de herfst, sneeuw en hagel. U hebt geen afdrukken van hagelbollen meer &amp;eacute;n u hoeft geen sneeuw meer van uw voorruit te schuiven. Ten opzichte van een garage is een carport een veel goedkopere oplossing en biedt deze ook voldoende bescherming.&lt;/p&gt;
    &lt;p&gt;&lt;a class="showMoreText" href="#"&gt;Meer info&lt;/a&gt;&lt;/p&gt;
    &lt;div class="moreText"&gt;
    &lt;p&gt;Dat u niet lukraak een carport kiest begrijpen we. Daarom hebben we verschillende types carports voor verschillende types van woningen in ons assortiment. Bekijk ook de verschillende afmetingen. Naargelang u een grote of kleine wagen heeft kan u een carport van een andere lengte kiezen. Bekijk ons assortiment hieronder!&lt;/p&gt;
    &lt;p&gt;&lt;a class="showLessText" href="#"&gt;Minder info&lt;/a&gt;&lt;/p&gt;
    &lt;/div&gt;
        </textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>