<h1 class="supporting title">responsive-show-phone</h1>
<div>
    <div class="responsive-show-phone">
        <p>This text is only visible on screens of 480 pixels wide or smaller.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of the CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-phone"&gt;
        &lt;p&gt;This text is only visible on screens of 480 pixels wide or smaller.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />