<h1 class="supporting title">responsive-hide-all</h1>
<div>
    <div class="responsive-hide-all">
        <p>This text is hidden on all screens.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-all"&gt;
        &lt;p&gt;This text is hidden on all screens.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />