<h1 class="supporting title">responsive-show-desktop</h1>
<div>
    <div class="responsive-show-desktop">
        <p>Deze tekst wordt enkel getoond op schermen van 1025 pixels breed of groter.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-desktop"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen van 1025 pixels breed of groter.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />