<h1 class="supporting title">responsive-hide-tablet</h1>
<div>
    <div class="responsive-hide-tablet">
        <p>Deze tekst is verborgen op schermen waarvan de breedte tussen 768 pixels en 1024 pixels ligt (beiden inclusief).</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-tablet"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen waarvan de breedte tussen 768 pixels en 1024 pixels ligt (beiden inclusief).&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />