<h1 class="supporting title">3 afbeeldingen naast elkaar</h1>
<div class="colm-grid visuals">
<div class="colm1-3"><img alt="" src="http://placehold.it/450x280" /></div>
<div class="colm1-3"><img alt="" src="http://placehold.it/450x280" /></div>
<div class="colm1-3"><img alt="" src="http://placehold.it/450x280" /></div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;div class="colm-grid visuals"&gt;
    &lt;div class="colm1-3"&gt;
        &lt;img alt="" src="http://placehold.it/450x280" /&gt;
    &lt;/div&gt;
    &lt;div class="colm1-3"&gt;
        &lt;img alt="" src="http://placehold.it/450x280" /&gt;
    &lt;/div&gt;
    &lt;div class="colm1-3"&gt;
        &lt;img alt="" src="http://placehold.it/450x280" /&gt;
    &lt;/div&gt;
&lt;/div&gt;
       </textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>