<h1 class="supporting title">2 images next to each other</h1>
<div class="colm-grid visuals">
<div class="colm1-2"><img alt="" src="http://placehold.it/684x280" /></div>
<div class="colm1-2"><img alt="" src="http://placehold.it/684x280" /></div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;div class="colm-grid visuals"&gt;
    &lt;div class="colm1-2"&gt;
        &lt;img alt="" src="http://placehold.it/684x280" /&gt;
    &lt;/div&gt;
    &lt;div class="colm1-2"&gt;
        &lt;img alt="" src="http://placehold.it/684x280" /&gt;
    &lt;/div&gt;
&lt;/div&gt;
       </textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>