<h1 class="supporting title">Flexslider</h1>

<p>Fore more configuration options, see <a href="https://github.com/woothemes/FlexSlider/wiki/FlexSlider-Properties" traget="_blank">Flexslider wiki</a></p>

<div>

<div class="flexslider">
<ul class="slides">
<li>
<a href="#"><img src="https://placeholdit.imgix.net/~text?txtsize=95&txt=Slide1&w=1240&h=380&txttrack=0&bg=777777&txtclr=cccccc" alt=""></a>
<h2>I haven't lost my mind; I know exactly where I left it.</h2>
</li>
<li>
<a href="#"><img src="https://placeholdit.imgix.net/~text?txtsize=95&txt=Slide2&w=1240&h=380&txttrack=0&bg=cccccc&txtclr=777777" alt=""></a>
<h2>The Moral Majority is neither.</h2>
</li>
<li>
<a href="#"><img src="https://placeholdit.imgix.net/~text?txtsize=95&txt=Slide3&w=1240&h=380&txttrack=0&bg=777777&txtclr=cccccc" alt=""></a>
<h2>Who messed with my anti-paranoia shot?</h2>
</li>
<li>
<a href="#"><img src="https://placeholdit.imgix.net/~text?txtsize=95&txt=Slide4&w=1240&h=380&txttrack=0&bg=cccccc&txtclr=777777" alt=""></a>
<h2>If you try to please everyone, somebody is not going to like it.</h2>
</li>
</ul>
</div>
<script type="text/javascript">
  require(['jquery','flexslider','domReady!'], function($){
    $('.flexslider').flexslider({animation: "slide"});
  });
</script>

</div>

<br />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="flexslider"&gt;
&lt;ul class="slides"&gt;
&lt;li&gt;
&lt;a href="#"&gt;&lt;img src="https://placeholdit.imgix.net/~text?txtsize=95&amp;txt=Slide1&amp;w=1240&amp;h=380&amp;txttrack=0&amp;bg=777777&amp;txtclr=cccccc" alt=""&gt;&lt;/a&gt;
&lt;h2&gt;I haven't lost my mind; I know exactly where I left it.&lt;/h2&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;a href="#"&gt;&lt;img src="https://placeholdit.imgix.net/~text?txtsize=95&amp;txt=Slide2&amp;w=1240&amp;h=380&amp;txttrack=0&amp;bg=cccccc&amp;txtclr=777777" alt=""&gt;&lt;/a&gt;
&lt;h2&gt;The Moral Majority is neither.&lt;/h2&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;a href="#"&gt;&lt;img src="https://placeholdit.imgix.net/~text?txtsize=95&amp;txt=Slide3&amp;w=1240&amp;h=380&amp;txttrack=0&amp;bg=777777&amp;txtclr=cccccc" alt=""&gt;&lt;/a&gt;
&lt;h2&gt;Who messed with my anti-paranoia shot?&lt;/h2&gt;
&lt;/li&gt;
&lt;li&gt;
&lt;a href="#"&gt;&lt;img src="https://placeholdit.imgix.net/~text?txtsize=95&amp;txt=Slide4&amp;w=1240&amp;h=380&amp;txttrack=0&amp;bg=cccccc&amp;txtclr=777777" alt=""&gt;&lt;/a&gt;
&lt;h2&gt;If you try to please everyone, somebody is not going to like it.&lt;/h2&gt;
&lt;/li&gt;
&lt;/ul&gt;
&lt;/div&gt;
&lt;script type="text/javascript"&gt;
  require(['jquery','flexslider','domReady!'], function($){
    $('.flexslider').flexslider({animation: "slide"});
  });
&lt;/script&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>
