<h1 class="supporting title">Gallery in lightbox voorbeeld 2</h1>

<div>
<div class="popup-gallery">
    <div class="colm-grid">
        <div class="colm1-5">
            <a href="//placehold.it/768x1024" title="Test image 1"><img src="//placehold.it/240x480" /></a>
        </div>
        <div class="colm4-5">
            <div class="colm-grid">
                <div class="colm3-5">
                    <a href="//placehold.it/1024x576" title="Test image 2"><img src="//placehold.it/588x235" /></a>
                </div>
                <div class="colm2-5">
                    <a href="//placehold.it/1024x576" title="Test image 3"><img src="//placehold.it/392x235" /></a>
                </div>
            </div>
            <div class="colm-grid">
                <div class="colm2-5">
                    <a href="//placehold.it/1024x576" title="Test image 4"><img src="//placehold.it/392x235" /></a>
                </div>
                <div class="colm3-5">
                    <a href="//placehold.it/1024x576" title="Test image 5"><img src="//placehold.it/588x235" /></a>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

<br />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="popup-gallery"&gt;
    &lt;div class="colm-grid"&gt;
        &lt;div class="colm1-5"&gt;
            &lt;a href="//placehold.it/768x1024" title="Test image 1"&gt;&lt;img src="//placehold.it/240x480" /&gt;&lt;/a&gt;
        &lt;/div&gt;
        &lt;div class="colm4-5"&gt;
            &lt;div class="colm-grid"&gt;
                &lt;div class="colm3-5"&gt;
                    &lt;a href="//placehold.it/1024x576" title="Test image 2"&gt;&lt;img src="//placehold.it/588x235" /&gt;&lt;/a&gt;
                &lt;/div&gt;
                &lt;div class="colm2-5"&gt;
                    &lt;a href="//placehold.it/1024x576" title="Test image 3"&gt;&lt;img src="//placehold.it/392x235" /&gt;&lt;/a&gt;
                &lt;/div&gt;
            &lt;/div&gt;
            &lt;div class="colm-grid"&gt;
                &lt;div class="colm2-5"&gt;
                    &lt;a href="//placehold.it/1024x576" title="Test image 4"&gt;&lt;img src="//placehold.it/392x235" /&gt;&lt;/a&gt;
                &lt;/div&gt;
                &lt;div class="colm3-5"&gt;
                    &lt;a href="//placehold.it/1024x576" title="Test image 5"&gt;&lt;img src="//placehold.it/588x235" /&gt;&lt;/a&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>