<h1 class="supporting title">Page-wide image</h1>
<div><img class="wide" alt="" src="https://placehold.it/1400x200/" /></div>
<p>No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. Oh, you're gonna be in a coma, all right. Say goodbye to these, because it's the last time! Marry me. Get me a vodka rocks. And a piece of toast. I'm a monster. I'm half machine. I'm a monster. It's a hug, Michael. I'm hugging you. There's so many poorly chosen words in that sentence. No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. That's why you always leave a note! There's so many poorly chosen words in that sentence. He'll want to use your yacht, and I don't want this thing smelling like fish. He'll want to use your yacht, and I don't want this thing smelling like fish.</p>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;div&gt;&lt;img class="wide" alt="" src="https://placehold.it/1400x200/" /&gt;&lt;/div&gt;
    &lt;p&gt;No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. Oh, you're gonna be in a coma, all right. Say goodbye to these, because it's the last time! Marry me. Get me a vodka rocks. And a piece of toast. I'm a monster. I'm half machine. I'm a monster. It's a hug, Michael. I'm hugging you. There's so many poorly chosen words in that sentence. No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. That's why you always leave a note! There's so many poorly chosen words in that sentence. He'll want to use your yacht, and I don't want this thing smelling like fish. He'll want to use your yacht, and I don't want this thing smelling like fish.
&lt;/p&gt;
        </textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>