<h1 class="supporting title">Video in lightbox thumbnail</h1>

<div>
<div class="se-grid cf">
    <div class="se-col se-col1-3">
        <a class="popup-video has-thumbnail" href="https://www.youtube.com/watch?v=LTvFsTbyILg">
            <img src="https://img.youtube.com/vi/LTvFsTbyILg/sddefault.jpg" />
        </a>
    </div>
    <div class="se-col se-col1-3">
        <a class="popup-video has-thumbnail" href="https://www.youtube.com/watch?v=LTvFsTbyILg">
            <img src="https://img.youtube.com/vi/LTvFsTbyILg/sddefault.jpg" />
        </a>
    </div>
    <div class="se-col se-col1-3">
        <a class="popup-video has-thumbnail" href="https://www.youtube.com/watch?v=LTvFsTbyILg">
            <img src="https://img.youtube.com/vi/LTvFsTbyILg/sddefault.jpg" />
        </a>
    </div>
</div>
</div>

<br />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;a class="popup-video has-thumbnail" href="https://www.youtube.com/watch?v=LTvFsTbyILg"&gt;
    &lt;img src="https://img.youtube.com/vi/LTvFsTbyILg/sddefault.jpg" /&gt;
&lt;/a&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<h1 class="supporting title">Video in lightbox textlink</h1>

<div>
    <a class="popup-video" href="https://www.youtube.com/watch?v=LTvFsTbyILg">Open video</a>
</div>

<br />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;a class="popup-video" href="https://www.youtube.com/watch?v=LTvFsTbyILg"&gt;Open video&lt;/a&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>