<h1 class="supporting title">Video</h1>
<p>By default, the video fills the available width on the page. Put it in a layout to keep it smaller (see 2nd example). It's also possible to fill out the empty columns with text.</p>

<div class="video-container">
    <div class="video-container"><iframe allowfullscreen="" frameborder="0" height="480" scrolling="no" src="https://www.youtube.com/embed/LTvFsTbyILg" width="640"></iframe></div>
</div>

<div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
        <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
        <textarea style="padding: .5em;" rows="10" cols="80">
&#x3C;div class=&#x22;video-container&#x22;&#x3E;
    &#x3C;div class=&#x22;video-container&#x22;&#x3E;&#x3C;iframe allowfullscreen=&#x22;&#x22; frameborder=&#x22;0&#x22; height=&#x22;480&#x22; scrolling=&#x22;no&#x22; src=&#x22;https://www.youtube.com/embed/LTvFsTbyILg&#x22; width=&#x22;640&#x22;&#x3E;&#x3C;/iframe&#x3E;&#x3C;/div&#x3E;
&#x3C;/div&#x3E;
        </textarea>
        <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
</div>

<div class="se-grid cf">
    <div class="se-col se-col1-4">
        &nbsp;
    </div>
    <div class="se-col se-col1-2">
        <div class="video-container">
            <div class="video-container"><iframe allowfullscreen="" frameborder="0" height="480" scrolling="no" src="https://www.youtube.com/embed/LTvFsTbyILg" width="640"></iframe></div>
        </div>
    </div>
    <div class="se-col se-col1-4">
        &nbsp;
    </div>
</div>

<div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
        <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
        <textarea style="padding: .5em;" rows="10" cols="80">
&#x3C;div class=&#x22;se-grid cf&#x22;&#x3E;
    &#x3C;div class=&#x22;se-col se-col1-4&#x22;&#x3E;
        &#x26;nbsp;
    &#x3C;/div&#x3E;
    &#x3C;div class=&#x22;se-col se-col1-2&#x22;&#x3E;
        &#x3C;div class=&#x22;video-container&#x22;&#x3E;
            &#x3C;div class=&#x22;video-container&#x22;&#x3E;&#x3C;iframe allowfullscreen=&#x22;&#x22; frameborder=&#x22;0&#x22; height=&#x22;480&#x22; scrolling=&#x22;no&#x22; src=&#x22;https://www.youtube.com/embed/LTvFsTbyILg&#x22; width=&#x22;640&#x22;&#x3E;&#x3C;/iframe&#x3E;&#x3C;/div&#x3E;
        &#x3C;/div&#x3E;
    &#x3C;/div&#x3E;
    &#x3C;div class=&#x22;se-col se-col1-4&#x22;&#x3E;
        &#x26;nbsp;
    &#x3C;/div&#x3E;
&#x3C;/div&#x3E;
        </textarea>
        <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
</div>