<h1 class="supporting title">Video</h1>
<p>Standaard vult de video de beschikbare breedte op de pagina. Plaats hem in een layoutvorm om kleiner te houden, zie 2de voorbeeld. Je kan de lege kolommen ook opvullen met tekst uiteraard</p>

<div class="video-container">
    <div class="video-container"><iframe allowfullscreen="" frameborder="0" height="480" scrolling="no" src="https://www.youtube.com/embed/LTvFsTbyILg" width="640"></iframe></div>
</div>

<div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
    <div class="htmlCode moreText">
        <p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
        <textarea style="padding: .5em;" rows="10" cols="80">
&#x3C;div class=&#x22;video-container&#x22;&#x3E;
    &#x3C;div class=&#x22;video-container&#x22;&#x3E;&#x3C;iframe allowfullscreen=&#x22;&#x22; frameborder=&#x22;0&#x22; height=&#x22;480&#x22; scrolling=&#x22;no&#x22; src=&#x22;https://www.youtube.com/embed/LTvFsTbyILg&#x22; width=&#x22;640&#x22;&#x3E;&#x3C;/iframe&#x3E;&#x3C;/div&#x3E;
&#x3C;/div&#x3E;
        </textarea>
        <p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
    </div>
</div>

<div class="se-grid cf">
    <div class="se-col se-col1-4">
        &nbsp;
    </div>
    <div class="se-col se-col1-2">
        <div class="video-container">
            <div class="video-container"><iframe allowfullscreen="" frameborder="0" height="480" scrolling="no" src="https://www.youtube.com/embed/LTvFsTbyILg" width="640"></iframe></div>
        </div>
    </div>
    <div class="se-col se-col1-4">
        &nbsp;
    </div>
</div>

<div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
    <div class="htmlCode moreText">
        <p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
        <textarea style="padding: .5em;" rows="10" cols="80">
&#x3C;div class=&#x22;se-grid cf&#x22;&#x3E;
    &#x3C;div class=&#x22;se-col se-col1-4&#x22;&#x3E;
        &#x26;nbsp;
    &#x3C;/div&#x3E;
    &#x3C;div class=&#x22;se-col se-col1-2&#x22;&#x3E;
        &#x3C;div class=&#x22;video-container&#x22;&#x3E;
            &#x3C;div class=&#x22;video-container&#x22;&#x3E;&#x3C;iframe allowfullscreen=&#x22;&#x22; frameborder=&#x22;0&#x22; height=&#x22;480&#x22; scrolling=&#x22;no&#x22; src=&#x22;https://www.youtube.com/embed/LTvFsTbyILg&#x22; width=&#x22;640&#x22;&#x3E;&#x3C;/iframe&#x3E;&#x3C;/div&#x3E;
        &#x3C;/div&#x3E;
    &#x3C;/div&#x3E;
    &#x3C;div class=&#x22;se-col se-col1-4&#x22;&#x3E;
        &#x26;nbsp;
    &#x3C;/div&#x3E;
&#x3C;/div&#x3E;
        </textarea>
        <p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
    </div>
</div>