<?php
// See Stores -> Configuration -> Social Media
if ($block->canRender()):
    $channels = $block->getChannels();
?>
<div class="social">
    <ul>
    <?php foreach ($channels as $channel => $label): ?>
        <?php if ($block->canRenderChannel($channel)): ?>
        <li>
            <a href="<?= $block->getChannelLink($channel) ?>"
                    title="<?= $block->getChannelAlt($channel, $label) ?>"
                    class="<?= $block->getChannelCssClass($channel) ?>">
                <?php if ($block->channelHasIcon($channel)): ?>
                <img src="<?= $block->getChannelIcon($channel) ?>"
                            alt="<?= $block->getChannelAlt($channel, $label) ?>" />
                <?php else: ?>
                    <span>&nbsp;</span>
                <?php endif; ?>
            </a>
        </li>
        <?php endif; ?>
    <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>
