<h1 class="supporting title">centered-icon</h1>

<div class="colm-grid">
    <div class="colm1-3">
        <div class="centered-icon-block">
            <img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/award.svg" />
            <h3>It's a hug, Michael. I'm hugging you.</h3>
            <p>I don't understand the question, and I won't respond to it.</p>
        </div>
    </div>
    <div class="colm1-3">
        <div class="centered-icon-block">
            <!-- begin svg -->
            <svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px"
                 viewBox="16 -48 64 64" enable-background="new 16 -48 64 64" xml:space="preserve">
                <path d="M47.996-9.951L40.821,8.739l-2.81-6.312L31.7,5.237l7.089-18.465c-3.306-2.688-5.42-6.786-5.42-11.378
                    c0-8.094,6.563-14.655,14.655-14.655c8.095,0,14.655,6.561,14.655,14.655c0,4.592-2.111,8.69-5.416,11.378l7.089,18.465
                    l-6.312-2.81l-2.809,6.312L48.057-9.951c-0.01,0-0.021,0-0.032,0C48.016-9.951,48.006-9.951,47.996-9.951L47.996-9.951
                    L47.996-9.951z M46.29-10.053L40.7,4.507L38.827,0.3l-4.208,1.873l5.534-14.415C41.966-11.086,44.051-10.316,46.29-10.053
                    L46.29-10.053L46.29-10.053z M55.897-12.242L61.43,2.173L57.223,0.3L55.35,4.507l-5.588-14.56
                    C52-10.316,54.085-11.086,55.897-12.242L55.897-12.242L55.897-12.242z M48.024-11.579c7.196,0,13.027-5.832,13.027-13.027
                    s-5.831-13.027-13.027-13.027c-7.193,0-13.026,5.832-13.026,13.027S40.831-11.579,48.024-11.579L48.024-11.579z M48.024-14.836
                    c5.397,0,9.771-4.375,9.771-9.77s-4.373-9.77-9.771-9.77c-5.394,0-9.77,4.375-9.77,9.77S42.631-14.836,48.024-14.836
                    L48.024-14.836z M48.024-16.464c4.497,0,8.143-3.646,8.143-8.142s-3.646-8.142-8.143-8.142c-4.495,0-8.142,3.646-8.142,8.142
                    S43.529-16.464,48.024-16.464L48.024-16.464z"/>
            </svg>
            <!-- end svg -->
            <h3>Really? Did nothing cancel?</h3>
            <p>Michael! As you may or may not know, Lindsay and I have hit a bit of a rough patch.</p>
        </div>
    </div>
    <div class="colm1-3">
        <div class="centered-icon-block">
            <img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/award.svg" />
            <h3>Now, when you do this without getting punched in the chest, you'll have more fun.</h3>
            <p>I'm a monster. Army had half a day. Guy's a pro. I don't understand the question, and I won't respond to it. But I bought a yearbook ad from you, doesn't that mean anything anymore? I'm afraid I just blue myself.</p>
        </div>
    </div>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="colm-grid"&gt;
    &lt;div class="colm1-3"&gt;
        &lt;div class="centered-icon-block"&gt;
            &lt;img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/award.svg" /&gt;
            &lt;h3&gt;It's a hug, Michael. I'm hugging you.&lt;/h3&gt;
            &lt;p&gt;I don't understand the question, and I won't respond to it.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    &lt;div class="colm1-3"&gt;
        &lt;div class="centered-icon-block"&gt;
            &lt;!-- begin svg --&gt;
            &lt;svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px" width="64px" height="64px"
                 viewBox="16 -48 64 64" enable-background="new 16 -48 64 64" xml:space="preserve"&gt;
                &lt;path d="M47.996-9.951L40.821,8.739l-2.81-6.312L31.7,5.237l7.089-18.465c-3.306-2.688-5.42-6.786-5.42-11.378
                    c0-8.094,6.563-14.655,14.655-14.655c8.095,0,14.655,6.561,14.655,14.655c0,4.592-2.111,8.69-5.416,11.378l7.089,18.465
                    l-6.312-2.81l-2.809,6.312L48.057-9.951c-0.01,0-0.021,0-0.032,0C48.016-9.951,48.006-9.951,47.996-9.951L47.996-9.951
                    L47.996-9.951z M46.29-10.053L40.7,4.507L38.827,0.3l-4.208,1.873l5.534-14.415C41.966-11.086,44.051-10.316,46.29-10.053
                    L46.29-10.053L46.29-10.053z M55.897-12.242L61.43,2.173L57.223,0.3L55.35,4.507l-5.588-14.56
                    C52-10.316,54.085-11.086,55.897-12.242L55.897-12.242L55.897-12.242z M48.024-11.579c7.196,0,13.027-5.832,13.027-13.027
                    s-5.831-13.027-13.027-13.027c-7.193,0-13.026,5.832-13.026,13.027S40.831-11.579,48.024-11.579L48.024-11.579z M48.024-14.836
                    c5.397,0,9.771-4.375,9.771-9.77s-4.373-9.77-9.771-9.77c-5.394,0-9.77,4.375-9.77,9.77S42.631-14.836,48.024-14.836
                    L48.024-14.836z M48.024-16.464c4.497,0,8.143-3.646,8.143-8.142s-3.646-8.142-8.143-8.142c-4.495,0-8.142,3.646-8.142,8.142
                    S43.529-16.464,48.024-16.464L48.024-16.464z"/&gt;
            &lt;/svg&gt;
            &lt;!-- end svg --&gt;
            &lt;h3&gt;Really? Did nothing cancel?&lt;/h3&gt;
            &lt;p&gt;Michael! As you may or may not know, Lindsay and I have hit a bit of a rough patch.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    &lt;div class="colm1-3"&gt;
        &lt;div class="centered-icon-block"&gt;
            &lt;img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/award.svg" /&gt;
            &lt;h3&gt;Now, when you do this without getting punched in the chest, you'll have more fun.&lt;/h3&gt;
            &lt;p&gt;I'm a monster. Army had half a day. Guy's a pro. I don't understand the question, and I won't respond to it. But I bought a yearbook ad from you, doesn't that mean anything anymore? I'm afraid I just blue myself.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />
