<h1 class="supporting title">max-width-XX</h1>
<p>You can add a class to a container so that its width is being limited with a certain percentage. It's also being centered. (max-width-90, max-width-80, max-width-70, max-width-60, max-width-50, max-width-40, max-width-30, max-width-20, max-width-10)</p>
<div class="max-width-80">
    <div class="se-grid cf">
        <div class="se-col se-col1-2">
            <h3>He'll want to use your yacht</h3>
            <p>I don't understand the question, and I won't respond to it. I'm afraid I just blue myself. Get me a vodka rocks. And a piece of toast. I don't understand the question, and I won't respond to it. Across from where? No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. No… but I'd like to be asked! Not tricks, Michael, illusions.</p>
        </div>
        <div class="se-col se-col1-2">
            <h3>Bad news. Andy Griffith turned us down</h3>
            <p>I'm real proud of you for coming, bro. I know you hate funerals. I've lived in darkness a long time. Over the years my eyes adjusted until the dark became my world and I could see. I love Halloween. The one time of year when everyone wears a mask … not just me.</p>
        </div>
    </div>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="max-width-80"&gt;
    &lt;div class="se-grid cf"&gt;
        &lt;div class="se-col se-col1-2"&gt;
            &lt;h3&gt;He'll want to use your yacht&lt;/h3&gt;
            &lt;p&gt;I don't understand the question, and I won't respond to it. I'm afraid I just blue myself. Get me a vodka rocks. And a piece of toast. I don't understand the question, and I won't respond to it. Across from where? No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. No… but I'd like to be asked! Not tricks, Michael, illusions.&lt;/p&gt;
        &lt;/div&gt;
        &lt;div class="se-col se-col1-2"&gt;
            &lt;h3&gt;Bad news. Andy Griffith turned us down&lt;/h3&gt;
            &lt;p&gt;I'm real proud of you for coming, bro. I know you hate funerals. I've lived in darkness a long time. Over the years my eyes adjusted until the dark became my world and I could see. I love Halloween. The one time of year when everyone wears a mask … not just me.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />

<div class="max-width-10">
    <img src="//placehold.it/640x480" />
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="max-width-10"&gt;
    &lt;img src="//placehold.it/640x480" /&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />