<h1 class="supporting title">vertical-center</h1>

<div class="se-grid cf vertical-center">
    <div class="se-col se-col1-2">
        <p>Sorry, checking all the water in this area; there's an escaped fish. The way I see it, every life is a pile of good things and bad things.…hey.…the good things don't always soften the bad things; but vice-versa the bad things don't necessarily spoil the good things and make them unimportant. No… It's a thing; it's like a plan, but with more greatness. It's art! A statement on modern society, 'Oh Ain't Modern Society Awful?'! Did I mention we have comfy chairs? I'm the Doctor, I'm worse than everyone's aunt. *catches himself* And that is not how I'm introducing myself. You've swallowed a planet! Did I mention we have comfy chairs? It's a fez. I wear a fez now. Fezes are cool. It's a fez. I wear a fez now. Fezes are cool. It's art! A statement on modern society, 'Oh Ain't Modern Society Awful?'!</p>
    </div>
    <div class="se-col se-col1-2">
        <h3>I'm the Doctor, I'm worse than everyone's aunt</h3>
        <p>It's art! A statement on modern society, 'Oh Ain't Modern Society Awful?'! I hate yogurt. It's just stuff with bits in. I hate yogurt. It's just stuff with bits in. Annihilate? No. No violence</p>
    </div>
    <div class="se-col se-col1-2">
        <h3>I am the last of my species, and I know how that weighs on the heart so don't lie to me!</h3>
        <p>Stop talking, brain thinking. Hush. Saving the world with meals on wheels. Aw, you're all Mr. Grumpy Face today. Sorry, checking all the water in this area; there's an escaped fish. Stop talking, brain thinking. Hush.</p>
    </div>
    <div class="se-col se-col1-2">
        <p>Did I mention we have comfy chairs? You hate me; you want to kill me! Well, go on! Kill me! KILL ME! I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why. Sorry, checking all the water in this area; there's an escaped fish. You know how I sometimes have really brilliant ideas? I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why. All I've got to do is pass as an ordinary human being. Simple. What could possibly go wrong? Aw, you're all Mr. Grumpy Face today. *Insistently* Bow ties are cool! Come on Amy, I'm a normal bloke, tell me what normal blokes do! Saving the world with meals on wheels. I'm the Doctor, I'm worse than everyone's aunt. *catches himself* And that is not how I'm introducing myself. You know how I sometimes have really brilliant ideas?</p>
    </div>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="se-grid cf vertical-center"&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;p&gt;Sorry, checking all the water in this area; there's an escaped fish. The way I see it, every life is a pile of good things and bad things.…hey.…the good things don't always soften the bad things; but vice-versa the bad things don't necessarily spoil the good things and make them unimportant. No… It's a thing; it's like a plan, but with more greatness. It's art! A statement on modern society, 'Oh Ain't Modern Society Awful?'! Did I mention we have comfy chairs? I'm the Doctor, I'm worse than everyone's aunt. *catches himself* And that is not how I'm introducing myself. You've swallowed a planet! Did I mention we have comfy chairs? It's a fez. I wear a fez now. Fezes are cool. It's a fez. I wear a fez now. Fezes are cool. It's art! A statement on modern society, 'Oh Ain't Modern Society Awful?'!&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;h3&gt;I'm the Doctor, I'm worse than everyone's aunt&lt;/h3&gt;
        &lt;p&gt;It's art! A statement on modern society, 'Oh Ain't Modern Society Awful?'! I hate yogurt. It's just stuff with bits in. I hate yogurt. It's just stuff with bits in. Annihilate? No. No violence&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;h3&gt;I am the last of my species, and I know how that weighs on the heart so don't lie to me!&lt;/h3&gt;
        &lt;p&gt;I am the last of my species, and I know how that weighs on the heart so don't lie to me!</h3>
        <p>Stop talking, brain thinking. Hush. Saving the world with meals on wheels. Aw, you're all Mr. Grumpy Face today. Sorry, checking all the water in this area; there's an escaped fish. Stop talking, brain thinking. Hush.&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;p&gt;Did I mention we have comfy chairs? You hate me; you want to kill me! Well, go on! Kill me! KILL ME! I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why. Sorry, checking all the water in this area; there's an escaped fish. You know how I sometimes have really brilliant ideas? I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why. All I've got to do is pass as an ordinary human being. Simple. What could possibly go wrong? Aw, you're all Mr. Grumpy Face today. *Insistently* Bow ties are cool! Come on Amy, I'm a normal bloke, tell me what normal blokes do! Saving the world with meals on wheels. I'm the Doctor, I'm worse than everyone's aunt. *catches himself* And that is not how I'm introducing myself. You know how I sometimes have really brilliant ideas?&lt;/p&gt;
    &lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />