<h1 class="supporting title">Columns : text only</h1>
<div class="se-grid cf">
<div class="se-col se-col1-2">
<p>Throw her in the brig. Leela, are you alright? You got wanged on the head. Belligerent and numerous. No! The kind with looting and maybe starting a few fires! Good news, everyone! There's a report on TV with some very bad news! Good man. Nixon's pro-war and pro-family. Soothe us with sweet lies. That's a popular name today. Little "e", big "B"? Hey, guess what you're accessories to.</p>
</div>
<div class="se-col se-col1-2">
<p>I videotape every customer that comes in here, so that I may blackmail them later. You guys aren't Santa! You're not even robots. How dare you lie in front of Jesus? Bender, you risked your life to save me! Why would a robot need to drink? Please, Don-Bot… look into your hard drive, and open your mercy file! Isn't it true that you have been paid for your testimony? Spare me your space age technobabble, Attila the Hun!</p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;div class="se-grid cf"&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;p&gt;Throw her in the brig. Leela, are you alright? You got wanged on the head. Belligerent and numerous. No! The kind with looting and maybe starting a few fires! Good news, everyone! There's a report on TV with some very bad news! Good man. Nixon's pro-war and pro-family. Soothe us with sweet lies. That's a popular name today. Little "e", big "B"? Hey, guess what you're accessories to.&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;p&gt;I videotape every customer that comes in here, so that I may blackmail them later. You guys aren't Santa! You're not even robots. How dare you lie in front of Jesus? Bender, you risked your life to save me! Why would a robot need to drink? Please, Don-Bot… look into your hard drive, and open your mercy file! Isn't it true that you have been paid for your testimony? Spare me your space age technobabble, Attila the Hun!&lt;/p&gt;
    &lt;/div&gt;
&lt;/div&gt;       </textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>
<hr />
<div class="se-grid cf">
<div class="se-col se-col1-3">
<p>Bender, you risked your life to save me! I was all of history's great robot actors - Acting Unit 0.8; Thespomat; David Duchovny! Well, then good news! It's a suppository. If rubbin' frozen dirt in your crotch is wrong, hey I don't wanna be right. We can't compete with Mom! Her company is big and evil! Ours is small and neutral! Bender, this is Fry's decision… and he made it wrong. So it's time for us to interfere in his life. Yeah, I do that with my stupidness.</p>
</div>
<div class="se-col se-col1-3">
<p>I love this planet! I've got wealth, fame, and access to the depths of sleaze that those things bring. For the last time, I don't like lilacs! Your 'first' wife was the one who liked lilacs! Actually, that's still true. Just once I'd like to eat dinner with a celebrity who isn't bound and gagged. Oh right. I forgot about the battle. That's right, baby. I ain't your loverboy Flexo, the guy you love so much. You even love anyone pretending to be him!</p>
</div>
<div class="se-col se-col1-3">
<p>I was having the most wonderful dream. Except you were there, and you were there, and you were there! I don't know what you did, Fry, but once again, you screwed up! Now all the planets are gonna start cracking wise about our mamas. Hey, guess what you're accessories to. Bender, hurry! This fuel's expensive! Also, we're dying! Hello Morbo, how's the family? OK, if everyone's finished being stupid. Daylight and everything. It's toe-tappingly tragic!</p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;div class="se-grid cf"&gt;
    &lt;div class="se-col se-col1-3"&gt;
        &lt;p&gt;Bender, you risked your life to save me! I was all of history's great robot actors - Acting Unit 0.8; Thespomat; David Duchovny! Well, then good news! It's a suppository. If rubbin' frozen dirt in your crotch is wrong, hey I don't wanna be right. We can't compete with Mom! Her company is big and evil! Ours is small and neutral! Bender, this is Fry's decision… and he made it wrong. So it's time for us to interfere in his life. Yeah, I do that with my stupidness.&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-3"&gt;
        &lt;p&gt;I love this planet! I've got wealth, fame, and access to the depths of sleaze that those things bring. For the last time, I don't like lilacs! Your 'first' wife was the one who liked lilacs! Actually, that's still true. Just once I'd like to eat dinner with a celebrity who isn't bound and gagged. Oh right. I forgot about the battle. That's right, baby. I ain't your loverboy Flexo, the guy you love so much. You even love anyone pretending to be him!&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-3"&gt;
        &lt;p&gt;I was having the most wonderful dream. Except you were there, and you were there, and you were there! I don't know what you did, Fry, but once again, you screwed up! Now all the planets are gonna start cracking wise about our mamas. Hey, guess what you're accessories to. Bender, hurry! This fuel's expensive! Also, we're dying! Hello Morbo, how's the family? OK, if everyone's finished being stupid. Daylight and everything. It's toe-tappingly tragic!&lt;/p&gt;
    &lt;/div&gt;
&lt;/div&gt;       </textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>
<hr />
<div class="se-grid cf">
<div class="se-col se-col3-5">
<p>I don't know what you did, Fry, but once again, you screwed up! Now all the planets are gonna start cracking wise about our mamas. So, how 'bout them Knicks? Daylight and everything. Now that the, uh, garbage ball is in space, Doctor, perhaps you can help me with my sexual inhibitions? You, a bobsleder!? That I'd like to see! I don't want to be rescued. Really?! Hey, tell me something. You've got all this money. How come you always dress like you're doing your laundry?</p>
</div>
<div class="se-col se-col2-5">
<p>Bender, you risked your life to save me! I was all of history's great robot actors - Acting Unit 0.8; Thespomat; David Duchovny! Well, then good news! It's a suppository. If rubbin' frozen dirt in your crotch is wrong, hey I don't wanna be right. We can't compete with Mom! Her company is big and evil! Ours is small and neutral! Bender, this is Fry's decision… and he made it wrong. So it's time for us to interfere in his life. Yeah, I do that with my stupidness.</p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="se-grid cf"&gt;
&lt;div class="se-col se-col3-5"&gt;
&lt;p&gt;I don't know what you did, Fry, but once again, you screwed up! Now all the planets are gonna start cracking wise about our mamas. So, how 'bout them Knicks? Daylight and everything. Now that the, uh, garbage ball is in space, Doctor, perhaps you can help me with my sexual inhibitions? You, a bobsleder!? That I'd like to see! I don't want to be rescued. Really?! Hey, tell me something. You've got all this money. How come you always dress like you're doing your laundry?&lt;/p&gt;
&lt;/div&gt;
&lt;div class="se-col se-col2-5"&gt;
&lt;p&gt;Bender, you risked your life to save me! I was all of history's great robot actors - Acting Unit 0.8; Thespomat; David Duchovny! Well, then good news! It's a suppository. If rubbin' frozen dirt in your crotch is wrong, hey I don't wanna be right. We can't compete with Mom! Her company is big and evil! Ours is small and neutral! Bender, this is Fry's decision… and he made it wrong. So it's time for us to interfere in his life. Yeah, I do that with my stupidness.&lt;/p&gt;
&lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />
