<h1 class="supporting title">Columns : empty too</h1>
<div class="se-grid cf">
    <div class="se-col se-col1-4 empty"><!-- --></div>
    <div class="se-col se-col1-2">
        <p>But I bought a yearbook ad from you, doesn't that mean anything anymore? Army had half a day. I've opened a door here that I regret. That's what it said on 'Ask Jeeves. ' Across from where? Say goodbye to these, because it's the last time! There's so many poorly chosen words in that sentence.</p>
    </div>
    <div class="se-col se-col1-4 empty"><!-- --></div>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="se-grid cf"&gt;
    &lt;div class="se-col se-col1-4 empty"&gt;&lt;!-- --&gt;&lt;/div&gt;
    &lt;div class="se-col se-col1-2"&gt;
        &lt;p&gt;But I bought a yearbook ad from you, doesn't that mean anything anymore? Army had half a day. I've opened a door here that I regret. That's what it said on 'Ask Jeeves. ' Across from where? Say goodbye to these, because it's the last time! There's so many poorly chosen words in that sentence.&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="se-col se-col1-4 empty"&gt;&lt;!-- --&gt;&lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />

<div class="colm-grid">
    <div class="colm1-4 empty"><!-- --></div>
    <div class="colm1-2">
        <p>But I bought a yearbook ad from you, doesn't that mean anything anymore? I've opened a door here that I regret. It's a hug, Michael. I'm hugging you. We just call it a sausage. First place chick is hot, but has an attitude, doesn't date magicians. There's so many poorly chosen words in that sentence. We just call it a sausage. I'm half machine. I'm a monster. As you may or may not know, Lindsay and I have hit a bit of a rough patch.</p>
    </div>
    <div class="colm1-4 empty"><!-- --></div>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
<div class="htmlCode moreText">
<p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="colm-grid"&gt;
    &lt;div class="colm1-4 empty"&gt;&lt;!-- --&gt;&lt;/div&gt;
    &lt;div class="colm1-2"&gt;
        &lt;p&gt;But I bought a yearbook ad from you, doesn't that mean anything anymore? I've opened a door here that I regret. It's a hug, Michael. I'm hugging you. We just call it a sausage. First place chick is hot, but has an attitude, doesn't date magicians. There's so many poorly chosen words in that sentence. We just call it a sausage. I'm half machine. I'm a monster. As you may or may not know, Lindsay and I have hit a bit of a rough patch.&lt;/p&gt;
    &lt;/div&gt;
    &lt;div class="colm1-4 empty"&gt;&lt;!-- --&gt;&lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Close html code</a></p>
</div>
</div>

<hr />
