<h1 class="supporting title">max-width-XX</h1>

<p>Je kan een class meegeven met een container zodat deze beperkt wordt met een percentage en ook gecentreerd wordt. (max-width-90, max-width-80, max-width-70, max-width-60, max-width-50, max-width-40, max-width-30, max-width-20, max-width-10)</p>

<div class="max-width-80">
    <div class="se-grid cf">
        <div class="se-col se-col1-2">
            <h3>Lorem ipsum</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
        <div class="se-col se-col1-2">
            <h3>Lorem ipsum</h3>
            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
        </div>
    </div>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="max-width-80"&gt;
    &lt;div class="se-grid cf"&gt;
        &lt;div class="se-col se-col1-2"&gt;
            &lt;h3&gt;Lorem ipsum&lt;/h3&gt;
            &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.&lt;/p&gt;
        &lt;/div&gt;
        &lt;div class="se-col se-col1-2"&gt;
            &lt;h3&gt;Lorem ipsum&lt;/h3&gt;
            &lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<div class="max-width-10">
    <img src="//placehold.it/640x480" />
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="max-width-10"&gt;
    &lt;img src="//placehold.it/640x480" /&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />