<div class="content-wrapper">
    <h1 class="supporting title">page-wide invert</h1>
</div>

<div class="page-wide invert" style="background-image: url('/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg');">
    <div class="page-wide-inner">
        <div class="se-grid cfi vertical-center">
            <div class="se-col se-col1-3">
                <h3>Aw, you're all Mr. Grumpy Face today.</h3>
            </div>
            <div class="se-col se-col2-3">
                <p>I'm the Doctor, I'm worse than everyone's aunt. *catches himself* And that is not how I'm introducing myself. You know when grown-ups tell you 'everything's going to be fine' and you think they're probably lying to make you feel better? They're not aliens, they're Earth…liens! It's a fez. I wear a fez now. Fezes are cool. Did I mention we have comfy chairs? It's a fez. I wear a fez now. Fezes are cool. Stop talking, brain thinking. Hush. I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why. You hate me; you want to kill me! Well, go on! Kill me! KILL ME! I am the last of my species, and I know how that weighs on the heart so don't lie to me!</p>
            </div>
        </div>
    </div>
</div>

<div class="content-wrapper">

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="page-wide invert" style="background-image: url('/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg');"&gt;
        &lt;div class="page-wide-inner"&gt;
            &lt;div class="se-grid cfi vertical-center"&gt;
                &lt;div class="se-col se-col1-3"&gt;
                    &lt;h3&gt;Aw, you're all Mr. Grumpy Face today.&lt;/h3&gt;
                &lt;/div&gt;
                &lt;div class="se-col se-col2-3"&gt;
                    &lt;p&gt;I'm the Doctor, I'm worse than everyone's aunt. *catches himself* And that is not how I'm introducing myself. You know when grown-ups tell you 'everything's going to be fine' and you think they're probably lying to make you feel better? They're not aliens, they're Earth…liens! It's a fez. I wear a fez now. Fezes are cool. Did I mention we have comfy chairs? It's a fez. I wear a fez now. Fezes are cool. Stop talking, brain thinking. Hush. I'm the Doctor. Well, they call me the Doctor. I don't know why. I call me the Doctor too. I still don't know why. You hate me; you want to kill me! Well, go on! Kill me! KILL ME! I am the last of my species, and I know how that weighs on the heart so don't lie to me!&lt;/p&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
    </div>

</div>
