<div class="content-wrapper">
    <h1 class="supporting title">page-wide invert ta-center</h1>
</div>

<div class="page-wide invert ta-center" style="background-image: url('/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg');">
    <div class="page-wide-inner">
        <h1>Aw, you're all Mr. Grumpy Face today.</h1>
        <hr class="cross" />
        <h2>Saving the world with meals on wheels</h2>
        <p>I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship. I am the last of my species, and I know how that weighs on the heart so don't lie to me! It's a fez. I wear a fez now. Fezes are cool. It's a fez. I wear a fez now. Fezes are cool. I am the Doctor, and you are the Daleks! They're not aliens, they're Earth…liens! I am the last of my species, and I know how that weighs on the heart so don't lie to me! Saving the world with meals on wheels. You know how I sometimes have really brilliant ideas? I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship.</p>
    </div>
</div>

<div class="content-wrapper">
    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="page-wide invert ta-center" style="background-image: url('/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg');"&gt;
        &lt;div class="page-wide-inner"&gt;
            &lt;h1&gt;Aw, you're all Mr. Grumpy Face today.&lt;/h1&gt;
            &lt;hr class="cross" /&gt;
            &lt;h2&gt;Saving the world with meals on wheels&lt;/h2&gt;
            &lt;p&gt;I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship. I am the last of my species, and I know how that weighs on the heart so don't lie to me! It's a fez. I wear a fez now. Fezes are cool. It's a fez. I wear a fez now. Fezes are cool. I am the Doctor, and you are the Daleks! They're not aliens, they're Earth…liens! I am the last of my species, and I know how that weighs on the heart so don't lie to me! Saving the world with meals on wheels. You know how I sometimes have really brilliant ideas? I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship.&lt;/p&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
    </div>
</div>
