<div class="content-wrapper">
    <h1 class="supporting title">page-wide invert</h1>
</div>

<div class="page-wide invert" style="background-image: url('/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg');">
    <div class="page-wide-inner">
        <div class="se-grid cfi vertical-center">
            <div class="se-col se-col1-3">
                <h3>Lorem ipsum et dolor sit amet</h3>
            </div>
            <div class="se-col se-col2-3">
                <p>Lorem ipsum et dolor sit amet, consectetur adipiscing elit. Integer imperdiet lacus eget turpis accumsan euismod. Donec lectus enim, semper vestibulum nisi at, condimentum ultricies lectus. Sed elementum elit diam, vitae dapibus dui bibendum nec. Cras ut ipsum eu enim dignissim dignissim. Fusce tempor convallis nibh, sagittis eleifend est fringilla sit amet. In id dictum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras eget gravida orci, vitae feugiat felis. Curabitur at erat nec lectus faucibus tempus ac bibendum nulla. Cras ut neque nec magna semper euismod sit amet pharetra leo. Duis convallis quis leo nec ornare. Phasellus auctor mauris eget mi lacinia sollicitudin. Ut sit amet dui tortor.</p>
            </div>
        </div>
    </div>
</div>

<div class="content-wrapper">

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="page-wide invert" style="background-image: url('/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg');"&gt;
        &lt;div class="page-wide-inner"&gt;
            &lt;div class="se-grid cfi vertical-center"&gt;
                &lt;div class="se-col se-col1-3"&gt;
                    &lt;h3&gt;Lorem ipsum et dolor sit amet&lt;/h3&gt;
                &lt;/div&gt;
                &lt;div class="se-col se-col2-3"&gt;
                    &lt;p&gt;Lorem ipsum et dolor sit amet, consectetur adipiscing elit. Integer imperdiet lacus eget turpis accumsan euismod. Donec lectus enim, semper vestibulum nisi at, condimentum ultricies lectus. Sed elementum elit diam, vitae dapibus dui bibendum nec. Cras ut ipsum eu enim dignissim dignissim. Fusce tempor convallis nibh, sagittis eleifend est fringilla sit amet. In id dictum velit. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Cras eget gravida orci, vitae feugiat felis. Curabitur at erat nec lectus faucibus tempus ac bibendum nulla. Cras ut neque nec magna semper euismod sit amet pharetra leo. Duis convallis quis leo nec ornare. Phasellus auctor mauris eget mi lacinia sollicitudin. Ut sit amet dui tortor.&lt;/p&gt;
                &lt;/div&gt;
            &lt;/div&gt;
        &lt;/div&gt;
    &lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
    </div>
    </div>

</div>
