<div class="content-wrapper">
    <h1 class="supporting title">page-wide-content</h1>
    <p>In order to add contentblocks to a page who need to be page-wide, a css class must be added to the body. You can do this by adding a layout update to a CMS page. The code below can be used for this.</p>

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
&lt;referenceContainer name="content"&gt;
&lt;block class="StudioEmma\Optimus\Block\PageWideContent" name="test.paragraph" template="Magento_Theme::paragraph.phtml"&gt;
&lt;arguments&gt;
&lt;argument name="label" xsi:type="string" translate="true"&gt; &lt;/argument&gt;
&lt;argument name="css_class" xsi:type="string"&gt;hidden&lt;/argument&gt;
&lt;/arguments&gt;
&lt;/block&gt;
&lt;/referenceContainer&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
    </div>

</div>

<div class="content-wrapper">
    <h1 class="supporting title">content-wrapper</h1>
    <p>To limit certain elements on the page, you can wrap it in a container with the class 'content-wrapper'.</p>
</div>

<div class="content-wrapper">
<p>All I've got to do is pass as an ordinary human being. Simple. What could possibly go wrong? Stop talking, brain thinking. Hush. Did I mention we have comfy chairs? I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship. Bow ties are cool! Come on Amy, I'm a normal bloke, tell me what normal blokes do!</p>
</div>

<div class="content-wrapper">

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="content-wrapper"&gt;
&lt;p&gt;All I've got to do is pass as an ordinary human being. Simple. What could possibly go wrong? Stop talking, brain thinking. Hush. Did I mention we have comfy chairs? I'm nobody's taxi service; I'm not gonna be there to catch you every time you feel like jumping out of a spaceship. Bow ties are cool! Come on Amy, I'm a normal bloke, tell me what normal blokes do!&lt;/p&gt;
&lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
    </div>

</div>

<div class="content-wrapper">
    <h1 class="supporting title">content-wrapper-wide</h1>
    <p>You can also add the class 'content-wrapper-wide'. It is then still limited, but the maximum width is a lot wider.</p>
</div>

<div class="content-wrapper-wide">
<img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg" />
</div>

<div class="content-wrapper">

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Show code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Copy &amp; paste the code below into the html view of your CMS page or static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="content-wrapper-wide"&gt;
&lt;img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg" /&gt;
&lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Close html code</a></p>
    </div>
    </div>

</div>
