<div class="content-wrapper">
    <h1 class="supporting title">page-wide-content</h1>
    <p>Om contentblokken toe te voegen aan een pagina die over de volledige paginabreedte lopen, moet er een css class toegevoegd worden aan de body. Dit kan je doen door een layout update toe te voegen aan de cms pagina. Deze code vind je hieronder.</p>

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Kopie&euml;r &amp; plak de onderstaande code in het layout update veld van uw CMS pagina in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
&lt;referenceContainer name="content"&gt;
&lt;block class="StudioEmma\Optimus\Block\PageWideContent" name="test.paragraph" template="Magento_Theme::paragraph.phtml"&gt;
&lt;arguments&gt;
&lt;argument name="label" xsi:type="string" translate="true"&gt; &lt;/argument&gt;
&lt;argument name="css_class" xsi:type="string"&gt;hidden&lt;/argument&gt;
&lt;/arguments&gt;
&lt;/block&gt;
&lt;/referenceContainer&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
    </div>
    </div>

</div>

<div class="content-wrapper">
    <h1 class="supporting title">content-wrapper</h1>
    <p>Om bepaalde delen van de pagina dan weer in te perken kan je er een div container rond zetten met de class 'content-wrapper'.</p>
</div>

<div class="content-wrapper">
<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac vulputate risus. Phasellus lacinia lectus dignissim, fermentum tortor in, hendrerit est. Nullam eget risus mi. Morbi sed velit ac sapien bibendum varius. Proin augue mauris, ullamcorper quis semper sit amet, tristique in nibh. Proin consequat enim quis diam venenatis, nec ultrices orci mattis. Nullam lorem enim, volutpat id felis nec, vehicula rutrum tellus.</p>
</div>

<div class="content-wrapper">

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="content-wrapper"&gt;
&lt;p&gt;Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas ac vulputate risus. Phasellus lacinia lectus dignissim, fermentum tortor in, hendrerit est. Nullam eget risus mi. Morbi sed velit ac sapien bibendum varius. Proin augue mauris, ullamcorper quis semper sit amet, tristique in nibh. Proin consequat enim quis diam venenatis, nec ultrices orci mattis. Nullam lorem enim, volutpat id felis nec, vehicula rutrum tellus.&lt;/p&gt;
&lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
    </div>
    </div>

</div>

<div class="content-wrapper">
    <h1 class="supporting title">content-wrapper-wide</h1>
    <p>Je kan de div container ook de class 'content-wrapper-wide' meegeven. Dan wordt hij nog steeds beperkt, maar is de maximum breedte wel veel breder.</p>
</div>

<div class="content-wrapper-wide">
<img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg" />
</div>

<div class="content-wrapper">

    <div class="sourceCode">
    <p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
    <div class="htmlCode moreText">
    <p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
    <textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="content-wrapper-wide"&gt;
&lt;img src="/static/frontend/Studioemma/optimus/nl_NL/StudioEmma_Optimus/img/example/texture.jpg" /&gt;
&lt;/div&gt;
    </textarea>
    <p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
    </div>
    </div>

</div>
