<h2 class="supporting title">Scheidingslijnen</h2>
<p>Standard ruler</p>
<hr />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;hr/&gt;</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<p>Dotted ruler</p>
<hr class="dotted" />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;hr class="dotted"/&gt;</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<p>Compact ruler (50%)</p>
<hr class="compact" />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;hr class="compact"/&gt;</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<p>Ruler extra margin</p>
<hr class="extra" />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;hr class="extra"/&gt;</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<p>Ruler fat</p>
<hr class="fat" />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;hr class="fat"/&gt;</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<p>Ruler with cross</p>
<hr class="cross" />
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">&lt;hr class="cross"/&gt;</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
