<h2 class="supporting title">Lijsten (genummerd &amp; ongenummerd)</h2>
<ol>
    <li>List item</li>
    <li>List item</li>
    <li>List item
        <ol>
            <li>List item level 2</li>
            <li>List item level 2
                <ol>
                    <li>List item level 3</li>
                    <li>List item level 3</li>
                </ol>
            </li>
        </ol>
    </li>
</ol>
<h4>Unordered list</h4>
<ul>
    <li>List item 01</li>
    <li>List item 02</li>
    <li>List item 03
        <ul>
            <li>List item level 2</li>
            <li>List item level 2
                <ul>
                    <li>List item level 3</li>
                    <li>List item level 3</li>
                </ul>
            </li>
        </ul>
    </li>
</ul>