<h2 class="supporting title">Status messages</h2>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-success success message">
                <div>Success : Thank you for subscribing. <a href="#">Link</a> with more info.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-error error message">
                <div>Error : Error with subscribing. <a href="#">Link</a> with more info.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-warning warning message">
                <div>Warning : Warning about subscribing. <a href="#">Link</a> with more info.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-notice warning message">
                <div>Notice : Notice about subscribing. <a href="#">Link</a> with more info.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-info info message">
                <div>Info : Information about subscribing. <a href="#">Link</a> with more info.</div>
            </div>
        </div>
    </div>
</div>