<h2 class="supporting title">Status boodschappen</h2>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-success success message">
                <div>Success : Bedankt voor het inschrijven.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-error error message">
                <div>Fout : Fout voor het inschrijven.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-warning warning message">
                <div>Waarschuwing : Waarschuwing voor het inschrijven.</div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-notice warning message">
                <div>Notice : Melding bij het inschrijven. </div>
            </div>
        </div>
    </div>
</div>

<div class="page messages">
    <div></div>
    <div>
        <div class="messages">
            <div class="message-info info message">
                <div>Info : Informatie voor het inschrijven.</div>
            </div>
        </div>
    </div>
</div>