<h2 class="supporting title">Titel met streep achter</h2>

<div class="striped">
	<div class="block-title">
		<strong>Uw titel</strong>
	</div>
</div>
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="striped"&gt;
	&lt;div class="block-title"&gt;
		&lt;strong&gt;Uw titel&lt;/strong&gt;
	&lt;/div&gt;
&lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<h2 class="supporting title">Titel op achtergrondafbeelding</h2>
<p>Valt op mobile/kleinere schermen terug naar titel zonder afbeelding</p>

<div class="page-title-wrapper has-background-image"><img class="background-image" src="//placehold.it/1240x100/333333/333333" alt="">
	<h1 id="page-title-heading" class="page-title"><span>Uw titel</span></h1>
</div>

<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
&lt;div class="page-title-wrapper has-background-image"&gt;&lt;img class="background-image" src="//placehold.it/1240x100/333333/333333" alt=""&gt;
	&lt;h1 id="page-title-heading" class="page-title"&gt;&lt;span&gt;Uw titel&lt;/span&gt;&lt;/h1&gt;
&lt;/div&gt;
</textarea><p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
