<h2 class="supporting title">Titles</h2>

<h1>This is an example of a h1 heading</h1>
<h2>This is an example of a h2 heading</h2>
<h3>This is an example of a h3 heading</h3>
<h4>This is an example of a h4 heading</h4>
<h5>This is an example of a h5 heading</h5>
<h6>This is an example of a h6 heading</h6>

<h2 class="supporting title">Titles followed by text</h2>
<h1>Title heading 1</h1>
<p>I am the man with no name, <strong>Zapp Brannigan!</strong> You know the worst thing about <a href="#">being a slave</a>? They make you work, but they don't pay you or <em>let you go</em>. It's okay, Bender. I like cooking too. Leela, are you alright? You got wanged on the head.</p>
<p><a href="#" class="primary action">Call to action</a></p>
<p>That's right, baby. I ain't your loverboy Flexo, the guy you love so much. You even love anyone pretending to be him! No, just a regular mistake. My fellow Earthicans, as I have explained in my book 'Earth in the Balance'', and the much more popular ''Harry Potter and the Balance of Earth', we need to defend our planet against pollution. Also dark wizards.</p>
<h2>Titel heading 2</h2>
<p>Guards! Bring me the forms I need to fill out to have her taken away! In our darkest hour, we can stand erect, with proud upthrust bosoms. You guys aren't Santa! You're not even robots. How dare you lie in front of Jesus?</p>
<h3>Titel heading 3</h3>
<p>You're going to do his laundry? I'm sure those <em>windmills</em> will keep them cool. Shinier than yours, meatbag. Well, thanks to the Internet, I'm now bored with sex. Is there a place on the web that panders to my lust for violence?</p>
<h4>Titel heading 4</h4>
<p>Michelle, I don't regret this, but I both rue and lament it. And until then, I can never die? Large bet on myself in round one. It's okay, Bender. I like cooking too. Who are you, my warranty?! Actually, that's still true.</p>
<h5>Titel heading 5</h5>
<p>I videotape every customer that comes in here, so that I may blackmail them later. Fetal stemcells, aren't those controversial? I suppose I could part with 'one' and still be feared… Hello, little man. I will destroy you!</p>
<h6>Titel heading 6</h6>
<p>Did you enjoy your meal, Mom? You drank it fast enough. Really? Did nothing cancel? Bad news. Andy Griffith turned us down. He didn't like his trailer. I care deeply for nature. Say goodbye to these, because it's the last time!</p>
<p>Not tricks, Michael, illusions. No, I did not kill Kitty. However, I am going to oblige and answer the nice officer's questions because I am an honest man with no secrets to hide. I hear the jury's still out on science.</p>


<h2 class="supporting title">Titles without heading tag (SEO proof)</h2>
<div class="h1">Title heading 1 </div>
<div class="h2">Title heading 2 with <a href="#">link</a> inside</div>
<div class="h3">Title heading 3 </div>
<div class="h4">Title heading 4 </div>
<div class="h5">Title heading 5 </div>
<div class="h6">Title heading 6 </div>
