<?php

// @codingStandardsIgnoreFile

/** @var $block \StudioEmma\Optimus\Block\Opengraph\Page */

$_helper_store = $this->helper('StudioEmma\Core\Helper\Store');

// tmp, needs refactoring, move page-config to block class
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$_page_config = $objectManager->get('Magento\Framework\View\Page\Config');
$_meta_title = strip_tags($_page_config->getTitle()->getShort());
$_meta_description = strip_tags($_page_config->getDescription());

/** @var Zend\Uri\Http $uri */
$uri = $this->getRequest()->getUri();
$ogUrl = $uri->getScheme() . '://' . $uri->getHost() . $this->getRequest()->getRequestUri();

$ogImageUrl = $block->getOgImageUrl();
$ogImageType = $block->getOgImageType();
$ogImageDimensions = $block->getOgImageDimensions(); // 0 = width, 1 = height;

?>

<meta property="og:locale" content="<?php echo $_helper_store->getLocale()?>" />
<meta property="og:type" content="website" />

<?php if (!empty($_meta_title)): ?>
    <meta property="og:title" content="<?php echo $_meta_title ?>" />
<?php endif; ?>

<?php if (!empty($_meta_description)): ?>
    <meta property="og:description" content="<?php echo $_meta_description ?>" />
<?php endif; ?>

<meta property="og:url" content="<?php echo $ogUrl; ?>" />
<meta property="og:site_name" content="<?php echo $this->getBaseUrl(); ?>" />

<meta property="og:image" content="<?php echo $ogImageUrl; ?>" />
<meta property="og:image:secure_url" content="<?php echo $ogImageUrl; ?>" />
<meta property="og:image:type" content="<?php echo $ogImageType; ?>" />
<meta property="og:image:width" content="<?php echo $ogImageDimensions[0]; ?>" />
<meta property="og:image:height" content="<?php echo $ogImageDimensions[1]; ?>" />
