<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<p>Below are links to pages that conatin examples of how to use html in static blocks and cms pages.</p>
<ul>
    <li><a href="/content/basic">Basic</a></li>
    <li><a href="/content/images">Images</a></li>
    <li><a href="/content/interaction">Interaction</a></li>
    <li><a href="/content/layout">Layout</a></li>
</ul>
