<p><?= __('Below are links to pages that contain examples for your content. Everything can be used in CMS pages and CMS static blocks.') ?></p>
<ul>
    <li>
        <a href="<?= $block->getUrl('content/basic') ?>">
            <span><?= __('Basic styling (titles, lists, quotes, etc)') ?></span>
        </a>
    </li>
    <li>
        <a href="<?= $block->getUrl('content/images') ?>">
            <span><?= __('Images & video (full-width image, 2 images next to eachother, etc)') ?></span>
        </a>
    </li>
    <li>
        <a href="<?= $block->getUrl('content/interaction') ?>">
            <span><?= __('Interaction (faq style, show more/less)') ?></span>
        </a>
    </li>
    <li>
        <a href="<?= $block->getUrl('content/layout') ?>">
            <span><?= __('Layout (structure examples. 1 column, 2 column, 3 columns etc)') ?></span>
        </a>
    </li>
    <li>
        <a href="<?= $block->getUrl('content/layout/wide') ?>">
            <span><?= __('Pagewide layout structures') ?></span>
        </a>
    </li>
    <li>
        <a href="<?= $block->getUrl('content/responsive') ?>">
            <span><?= __('Classes for showing and hiding elements on certain screenwidths') ?></span>
        </a>
    </li>
    <li>
        <a href="<?= $block->getUrl('content/specific') ?>">
            <span><?= __('Specific contentblocks for your site') ?></span>
        </a>
    </li>
</ul>
