<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<p class="supporting"><a href="/content">Back to overview</a></p>

<script type="text/javascript">
require(["jquery"], function($){
    $(document).ready(function ($) {
        // ==============================================
        // Toggle html example codes
        // ==============================================

        $(".showHtml").click(function() {
            $(this).parent().next('.htmlCode').addClass('toggled');
            $(this).parent().next('.htmlCode').find('textarea').select();
            $(this).hide();
            return false;
        });

        $(".hideHtml").click(function() {
            $(this).parent().parent().removeClass('toggled');
            $(this).parent().parent().prev().find('.showHtml').show();
            return false;
        });
    });
});
</script>