<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<p class="supporting"><a href="/content">Back to overview</a></p>


<section class="content-row">
<h1 class="supporting-title">Accordeon</h1>
<div class="accordion">
<h4><a href="#">Titel met H4</a></h4>
<div>
<p>Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.</p>
</div>
<h3><a href="#">Titel met H3</a></h3>
<div>
<p>Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.</p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">    &lt;div class="accordion"&gt;
    &lt;h4&gt;&lt;a href="#"&gt;Titel met H4&lt;/a&gt;&lt;/h4&gt;
    &lt;div&gt;
    &lt;p&gt;Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.&lt;/p&gt;
    &lt;/div&gt;
    &lt;h3&gt;&lt;a href="#"&gt;Titel met H3&lt;/a&gt;&lt;/h3&gt;
    &lt;div&gt;
    &lt;p&gt;Elke A tag binnen een H4 of H3 in een class='accordion' container zal het eerstvolgende kind tevoorschijn brengen onclick. Accordeon style dus.&lt;/p&gt;
    &lt;/div&gt;
    &lt;/div&gt;
        </textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
<div>
<h1 class="supporting-title">Toon meer / minder tekst</h1>
<p>Heeft u geen garage, maar wel ruimte voor bijvoorbeeld een <strong>carport</strong>? Dan moet u zeker overwegen eentje aan te schaffen. Een carport is een overkapping voor uw auto en helpt uw auto te beschermen tegen vallende takken in de herfst, sneeuw en hagel. U hebt geen afdrukken van hagelbollen meer &eacute;n u hoeft geen sneeuw meer van uw voorruit te schuiven. Ten opzichte van een garage is een carport een veel goedkopere oplossing en biedt deze ook voldoende bescherming.</p>
<p><a class="showMoreText" href="#">Meer info</a></p>
<div class="moreText">
<p>Dat u niet lukraak een carport kiest begrijpen we. Daarom hebben we verschillende types carports voor verschillende types van woningen in ons assortiment. Bekijk ook de verschillende afmetingen. Naargelang u een grote of kleine wagen heeft kan u een carport van een andere lengte kiezen. Bekijk ons assortiment hieronder!</p>
<p><a class="showLessText" href="#">Minder info</a></p>
</div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">    &lt;h1&gt;Show more / less text&lt;/h1&gt;
    &lt;p&gt;Heeft u geen garage, maar wel ruimte voor bijvoorbeeld een &lt;strong&gt;carport&lt;/strong&gt;? Dan moet u zeker overwegen eentje aan te schaffen. Een carport is een overkapping voor uw auto en helpt uw auto te beschermen tegen vallende takken in de herfst, sneeuw en hagel. U hebt geen afdrukken van hagelbollen meer &amp;eacute;n u hoeft geen sneeuw meer van uw voorruit te schuiven. Ten opzichte van een garage is een carport een veel goedkopere oplossing en biedt deze ook voldoende bescherming.&lt;/p&gt;
    &lt;p&gt;&lt;a class="showMoreText" href="#"&gt;Meer info&lt;/a&gt;&lt;/p&gt;
    &lt;div class="moreText"&gt;
    &lt;p&gt;Dat u niet lukraak een carport kiest begrijpen we. Daarom hebben we verschillende types carports voor verschillende types van woningen in ons assortiment. Bekijk ook de verschillende afmetingen. Naargelang u een grote of kleine wagen heeft kan u een carport van een andere lengte kiezen. Bekijk ons assortiment hieronder!&lt;/p&gt;
    &lt;p&gt;&lt;a class="showLessText" href="#"&gt;Minder info&lt;/a&gt;&lt;/p&gt;
    &lt;/div&gt;
        </textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>
</section>

<script type="text/javascript">

require(["jquery"], function($){
    $(document).ready(function ($) {
        // ==============================================
        // Toggle html example codes
        // ==============================================

        $(".showHtml").click(function() {
            $(this).parent().next('.htmlCode').addClass('toggled');
            $(this).parent().next('.htmlCode').find('textarea').select();
            $(this).hide();
            return false;
        });

        $(".hideHtml").click(function() {
            $(this).parent().parent().removeClass('toggled');
            $(this).parent().parent().prev().find('.showHtml').show();
            return false;
        });
    });
});

</script>
