<?php
//
//  Resposive show hide examples
//  ____________________________
?>
<p class="supporting"><a href="/content">Back to overview</a></p>
<h4 class="supporting">Dit document beschrijft de verschillende classes die je kan inzetten om zaken op uw pagina's te tonen of te verbergen bij bepaalde groottes van schermen.</h4>

<script type="text/javascript">
require(["jquery"], function($){
    $(document).ready(function ($) {
        // ==============================================
        // Toggle html example codes
        // ==============================================

        $(".showHtml").click(function() {
            $(this).parent().next('.htmlCode').addClass('toggled');
            $(this).parent().next('.htmlCode').find('textarea').select();
            $(this).hide();
            return false;
        });

        $(".hideHtml").click(function() {
            $(this).parent().parent().removeClass('toggled');
            $(this).parent().parent().prev().find('.showHtml').show();
            return false;
        });
    });
});
</script>