<?php
//
//  Resposive show hide examples
//  ____________________________
?>
<p class="supporting"><a href="/content">Back to overview</a></p>

<section class="content-row">

<h4 class="supporting">Dit document beschrijft de verschillende classes die je kan inzetten om zaken op uw pagina's te tonen of te verbergen bij bepaalde groottes van schermen.</h4>

<h1 class="supporting title">responsive-show-phone</h1>
<div>
    <div class="responsive-show-phone">
        <p>Deze tekst wordt enkel getoond op schermen van 480 pixels breed of kleiner.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-phone"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen van 480 pixels breed of kleiner.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-show-smallscreen</h1>
<div>
    <div class="responsive-show-smallscreen">
        <p>Deze tekst wordt enkel getoond op schermen van 768 pixels breed of kleiner. Dit komt overeen met het punt waarop de mobiele navigatie begint.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-smallscreen"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen van 768 pixels breed of kleiner. Dit komt overeen met het punt waarop de mobiele navigatie begint.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-show-tablet</h1>
<div>
    <div class="responsive-show-tablet">
        <p>Deze tekst wordt enkel getoond op schermen waarvan de breedte tussen 768 pixels en 1024 pixels ligt (beiden inclusief).</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-tablet"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen waarvan de breedte tussen 768 pixels en 1024 pixels ligt (beiden inclusief).&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-show-mobile</h1>
<div>
    <div class="responsive-show-mobile">
        <p>Deze tekst wordt enkel getoond op schermen van 1024 pixels breed of kleiner.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-mobile"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen van 1024 pixels breed of kleiner.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-show-desktop</h1>
<div>
    <div class="responsive-show-desktop">
        <p>Deze tekst wordt enkel getoond op schermen van 1025 pixels breed of groter.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-desktop"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen van 1025 pixels breed of groter.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-show-widescreen</h1>
<div>
    <div class="responsive-show-widescreen">
        <p>Deze tekst wordt enkel getoond op schermen van 1441 pixels breed of groter.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-show-widescreen"&gt;
        &lt;p&gt;Deze tekst wordt enkel getoond op schermen van 1441 pixels breed of groter.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />


<h1 class="supporting title">responsive-hide-phone</h1>
<div>
    <div class="responsive-hide-phone">
        <p>Deze tekst is verborgen op schermen van 480 pixels breed of kleiner.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-phone"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 480 pixels breed of kleiner.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-hide-smallscreen</h1>
<div>
    <div class="responsive-hide-smallscreen">
        <p>Deze tekst is verborgen op schermen van 768 pixels breed of kleiner. Dit komt overeen met het punt waarop de mobiele navigatie begint.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-smallscreen"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 768 pixels breed of kleiner. Dit komt overeen met het punt waarop de mobiele navigatie begint.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-hide-tablet</h1>
<div>
    <div class="responsive-hide-tablet">
        <p>Deze tekst is verborgen op schermen waarvan de breedte tussen 768 pixels en 1024 pixels ligt (beiden inclusief).</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-tablet"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen waarvan de breedte tussen 768 pixels en 1024 pixels ligt (beiden inclusief).&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-hide-mobile</h1>
<div>
    <div class="responsive-hide-mobile">
        <p>Deze tekst is verborgen op schermen van 1024 pixels breed of kleiner.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-mobile"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 1024 pixels breed of kleiner.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-hide-desktop</h1>
<div>
    <div class="responsive-hide-desktop">
        <p>Deze tekst is verborgen op schermen van 1025 pixels breed of groter.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-desktop"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 1025 pixels breed of groter.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-hide-widescreen</h1>
<div>
    <div class="responsive-hide-widescreen">
        <p>Deze tekst is verborgen op schermen van 1441 pixels breed of groter.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-widescreen"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 1441 pixels breed of groter.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-hide-all</h1>
<div>
    <div class="responsive-hide-all">
        <p>Deze tekst is verborgen op alle schermen.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-hide-all"&gt;
        &lt;p&gt;Deze tekst is verborgen op alle schermen.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-show-small</h1>
<div>
    <div class="responsive-vertical-show-small">
        <p>Deze tekst is enkel zichtbaar op schermen van 480 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-show-small"&gt;
        &lt;p&gt;Deze tekst is enkel zichtbaar op schermen van 480 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-show-medium</h1>
<div>
    <div class="responsive-vertical-show-medium">
        <p>Deze tekst is enkel zichtbaar op schermen van 640 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-show-medium"&gt;
        &lt;p&gt;Deze tekst is enkel zichtbaar op schermen van 640 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-show-large</h1>
<div>
    <div class="responsive-vertical-show-large">
        <p>Deze tekst is enkel zichtbaar op schermen van 768 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-show-large"&gt;
        &lt;p&gt;Deze tekst is enkel zichtbaar op schermen van 768 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-show-extra-large</h1>
<div>
    <div class="responsive-vertical-show-extra-large">
        <p>Deze tekst is enkel zichtbaar op schermen van 1024 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-show-extra-large"&gt;
        &lt;p&gt;Deze tekst is enkel zichtbaar op schermen van 1024 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-hide-small</h1>
<div>
    <div class="responsive-vertical-hide-small">
        <p>Deze tekst is verborgen op schermen van 480 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-hide-small"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 480 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-hide-medium</h1>
<div>
    <div class="responsive-vertical-hide-medium">
        <p>Deze tekst is verborgen op schermen van 640 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-hide-medium"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 640 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-hide-large</h1>
<div>
    <div class="responsive-vertical-hide-large">
        <p>Deze tekst is verborgen op schermen van 768 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-hide-large"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 768 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />

<h1 class="supporting title">responsive-vertical-hide-extra-large</h1>
<div>
    <div class="responsive-vertical-hide-extra-large">
        <p>Deze tekst is verborgen op schermen van 1024 pixels hoog of lager.</p>
    </div>
</div>
<div class="sourceCode">
<p><a class="showHtml" style="display: inline;" href="#"><?php echo __('Toon code') ?></a></p>
<div class="htmlCode moreText">
<p>Kopie&euml;r &amp; plak de onderstaande code in de html weergave uw CMS pagina of static block in Magento</p>
<textarea style="padding: .5em;" rows="10" cols="80">
    &lt;div class="responsive-vertical-hide-extra-large"&gt;
        &lt;p&gt;Deze tekst is verborgen op schermen van 1024 pixels hoog of lager.&lt;/p&gt;
    &lt;/div&gt;
</textarea>
<p><a class="hideHtml" href="#">Sluit htmlcode</a></p>
</div>
</div>

<hr />





</section>

<script type="text/javascript">

require(["jquery"], function($){
    $(document).ready(function ($) {
        // ==============================================
        // Toggle html example codes
        // ==============================================

        $(".showHtml").click(function() {
            $(this).parent().next('.htmlCode').addClass('toggled');
            $(this).parent().next('.htmlCode').find('textarea').select();
            $(this).hide();
            return false;
        });

        $(".hideHtml").click(function() {
            $(this).parent().parent().removeClass('toggled');
            $(this).parent().parent().prev().find('.showHtml').show();
            return false;
        });
    });
});

</script>
