<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<div class="content-wrapper">
    <p class="supporting">
        <a href="<?= $block->getUrl('content') ?>">
            <span><?= __('Back to overview') ?></span>
        </a>
    </p>
    <h4 class="supporting">This document shows specific contentblocks which you can use to add to your website.</h4>
</div>

<script type="text/javascript">
require(["jquery"], function($){
    $(document).ready(function ($) {
        // ==============================================
        // Toggle html example codes
        // ==============================================

        $(".showHtml").click(function() {
            $(this).parent().next('.htmlCode').addClass('toggled');
            $(this).parent().next('.htmlCode').find('textarea').select();
            $(this).hide();
            return false;
        });

        $(".hideHtml").click(function() {
            $(this).parent().parent().removeClass('toggled');
            $(this).parent().parent().prev().find('.showHtml').show();
            return false;
        });
    });
});
</script>
